"""add_actual_audit_mode_to_audits

Revision ID: 10d8ae5e2d2d
Revises: 4911049476c9
Create Date: 2025-12-23 09:49:05.763401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d8ae5e2d2d'
down_revision: Union[str, None] = '4911049476c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('actual_audit_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'actual_audit_mode')
    # ### end Alembic commands ###
