"""Add audit_mode column

Revision ID: 23b06aee17e6
Revises: 4efa702093cc
Create Date: 2025-12-16 16:33:53.066179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23b06aee17e6'
down_revision: Union[str, None] = '4efa702093cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('audit_mode', sa.String(length=20), nullable=True))
    op.alter_column('audits', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('glossaries', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('glossaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('glossaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('glossary_terms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('glossary_terms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('glossaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('glossaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('glossaries', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('audits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('audits', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('audits', 'audit_mode')
    # ### end Alembic commands ###
