"""Add screenshot columns to audits

Revision ID: 24ff8bb67b93
Revises: 23b06aee17e6
Create Date: 2025-12-16 17:36:02.031454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ff8bb67b93'
down_revision: Union[str, None] = '23b06aee17e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('original_screenshot', sa.Text(), nullable=True))
    op.add_column('audits', sa.Column('audit_screenshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'audit_screenshot')
    op.drop_column('audits', 'original_screenshot')
    # ### end Alembic commands ###
