"""add_api_cost_fields_to_audits

Revision ID: a45003b818b1
Revises: 10d8ae5e2d2d
Create Date: 2025-12-23 10:04:35.590718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45003b818b1'
down_revision: Union[str, None] = '10d8ae5e2d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('api_cost_usd', sa.Float(), nullable=True))
    op.add_column('audits', sa.Column('api_input_tokens', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('api_output_tokens', sa.Integer(), nullable=True))
    op.add_column('audits', sa.Column('api_duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'api_duration_ms')
    op.drop_column('audits', 'api_output_tokens')
    op.drop_column('audits', 'api_input_tokens')
    op.drop_column('audits', 'api_cost_usd')
    # ### end Alembic commands ###
