"""Add glossary_id to audits

Revision ID: e673464d4596
Revises: 24ff8bb67b93
Create Date: 2025-12-16 17:41:33.170247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e673464d4596'
down_revision: Union[str, None] = '24ff8bb67b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('glossary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audits', 'glossaries', ['glossary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audits', type_='foreignkey')
    op.drop_column('audits', 'glossary_id')
    # ### end Alembic commands ###
