"""add_blocked_reason

Revision ID: f2615f6b3a6f
Revises: a45003b818b1
Create Date: 2025-12-28 22:21:56.338404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2615f6b3a6f'
down_revision: Union[str, None] = 'a45003b818b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('blocked_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'blocked_reason')
    # ### end Alembic commands ###
